#version 460 core
layout(local_size_x = 256) in;

layout(std430, binding = 5) buffer prefix_sums {
    uint prefix[];
};

layout(std430, binding = 6) readonly buffer workgroup_totals {
    uint group_totals[];
};

uniform uint total_faces;

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= total_faces) return;

    uint group_id = gl_WorkGroupID.x;
    prefix[gid] += group_totals[group_id];
}
