#version 460 core

layout(local_size_x = 1) in; // only need 1 thread

layout(std430, binding = 3) buffer FaceCounter {
    uint face_count;
};

layout(std430, binding = 4) buffer IndirectSSBO {
    uint count;
    uint instanceCount;
    uint first;
    uint baseInstance;
} indirect;

void main() {
	face_count = 0;
    // Reset indirect_ssbo
    indirect.count = 0;
    indirect.instanceCount = 0;
    indirect.first = 0;
    indirect.baseInstance = 0;
}
