name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-type: [debug, release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ clang \
            libgl1-mesa-dev xorg-dev  # OpenGL + X11 dev headers

      - name: Configure with CMake preset
        run: cmake --preset ${{ matrix.build-type }}

      - name: Build with CMake preset
        run: cmake --build --preset ${{ matrix.build-type }}
