name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: # nightly full matrix
    - cron: '0 2 * * *'  # 2 AM UTC

jobs:
  fast-build:
    if: github.event_name != 'schedule'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build-type: [release]  # Only Release for fast CI
        tracy: [ON]            # Only test TRACY ON in fast CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ matrix.build-type }}-${{ matrix.tracy }}-v1

      # --- Linux dependencies ---
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ clang \
               libgl1-mesa-dev xorg-dev \
               libwayland-dev wayland-protocols extra-cmake-modules \
               libxkbcommon-dev

      # --- Windows dependencies ---
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          choco install ninja --yes
        shell: powershell

      # --- Configure CMake ---
      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake --preset ${{ matrix.build-type }} -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl.exe -DTRACY_ENABLE=${{ matrix.tracy }}

      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: cmake --preset ${{ matrix.build-type }} -DTRACY_ENABLE=${{ matrix.tracy }}

    
# Build step for Windows
      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake --build --preset ${{ matrix.build-type }}

# Build step for Linux
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: cmake --build --preset ${{ matrix.build-type }}


  full-matrix:
    if: github.event_name == 'schedule'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build-type: [debug, release]
        tracy: [OFF, ON]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ matrix.build-type }}-${{ matrix.tracy }}-v1

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ clang \
               libgl1-mesa-dev xorg-dev \
               libwayland-dev wayland-protocols extra-cmake-modules \
               libxkbcommon-dev

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          choco install ninja --yes
        shell: powershell

# Configure CMake (Windows)
      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake --preset ${{ matrix.build-type }} -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl.exe -DTRACY_ENABLE=${{ matrix.tracy }}

# Configure CMake (Linux)
      - name: Configure CMake (Linux)
        if: runner.os == 'Linux'
        run: cmake --preset ${{ matrix.build-type }} -DTRACY_ENABLE=${{ matrix.tracy }}


# Build step for Windows
      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake --build --preset ${{ matrix.build-type }}

# Build step for Linux
      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: cmake --build --preset ${{ matrix.build-type }}

